### PR TITLE
refactor: get rid of fast-deep-equal-library, and use fast-equals instead

### LINKED ISSUE #392: [FEAT] Get rid of `fast-deep-equal` library.
## Is your feature request related to a problem? Please describe.
The `[fast-deep-equal library](https://github.com/epoberezkin/fast-deep-equal)` seems to be no longer supported (last commit four years ago), and it causes troubles over and over. 

## Describe the solution you'd like
It is a good idea to get rid of it and find some other/newer/evergreen library instead. Eventually, we could write our own custom `equal` function since that's the only function we use out of it.

Possible solutions:
- https://www.measurethat.net/Benchmarks/Show/19037/0/fast-deep-equal-vs-jsonstringify-equality-comparison-fo#latest_results_block
- https://github.com/planttheidea/fast-equals

## What are the acceptance criteria?
- The `fast-deep-equal` library no longer exists in the dependencies.
- Every component using the `fast-deep-equal` library works as before with the new solution.

### PR DESCRIPTION
**Pull request by AlanLes**
## Description
- gets rid of `fast-deep-equal` library,
- uses `fast-equals` library instead,
- updates some packages with no conflicts and major changes, 

## Related Issue
Closes #392 

## How Has This Been Tested?
- Run `pnpm serve`, and check if everything still works.
- Run `pnpm check:types` and see no errors.
- Clicked through the components in Storybook.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mateuszkulpa** [comment]
@AlanLes 
WDYT about creating a facade for this library? I mean, creating a new internal utility and importing the external library only there. This would help us migrate to another library or switch to an in-house solution.

**Comment by pspaczek** [comment]
IMO you should exclude the stylelint changes from this pull request.

**Comment by AlanLes** [comment]
@mateuszkulpa sounds like a good idea! 👍 
@pspaczek ok, I'll do that 👍

**Review by mateuszkulpa — APPROVED** [review]
LGTM 👏

**Pull request merged**
