### PR TITLE
feat/ui side panel header: new design 

### PR DESCRIPTION
**Pull request by AlanLes**
- change `flex-direction` and `justify-content` in the UiSidePanel's header part - keep consistency with the newest design; add css variables for these two properties as well
- change `align-self` of the UiSidePanel's close element; add css variable for this property
- add `padding-block` and `padding-inline` to the `close` part of the UiSidePanel; add `margin`, `display`, and `align-items` to the `label` of the UiSidePanel

### BEFORE
image

### AFTER
image

### DESIGN
image

### FINAL LOOK ON REAL ENVIRONMENT
https://github.com/infermedica/component-library/assets/13744352/9ba23d4f-046c-4521-8d46-29fb178233bc

### CODE REVIEW

**Comment by pspaczek** [comment]
@AlanLes please share a link to the design. I can use screen to validate changes. And second thing. Triage still keeps close button on top. We can include breaking changes just like that.

**Comment by AlanLes** [comment]
> @AlanLes please share a link to the design. I can use screen to validate changes. And second thing. Triage still keeps close button on top. We can include breaking changes just like that.

Here's link to the design :) 
https://www.figma.com/file/1kbp6jo7M1Q0eaCzQKWYzv/Post-Triage-Follow-Up-%26-Intake-(Unified-UI-iteration-1)?type=design&node-id=141-206553&mode=design&t=2lHdiZACKCrT0M35-0

And second thing: as I'm aware - unified design is both for Triage and for Intake - generally for MGP - so I believe Triage won't keep close button on top.

**Comment by pspaczek** [comment]
Yes, but. When you add visual breaking changes now you freeze package updates for Triage. And second thing, we should have a bigger picture. We have button on top. Why we want to remove it... Why we can't keep it as an alternative for CL users out of company?

**Comment by pspaczek** [comment]
> > @AlanLes please share a link to the design. I can use screen to validate changes. And second thing. Triage still keeps close button on top. We can include breaking changes just like that.
> 
> @pspaczek Here's link to the design :) https://www.figma.com/file/1kbp6jo7M1Q0eaCzQKWYzv/Post-Triage-Follow-Up-%26-Intake-(Unified-UI-iteration-1)?type=design&node-id=141-206553&mode=design&t=2lHdiZACKCrT0M35-0
> 
> And second thing: as I'm aware - unified design is both for Triage and for Intake - generally for MGP - so I believe Triage won't keep close button on top.

Zrzut ekranu 2023-08-18 o 09 46 29
I can't find the design where the cross is in the same line when I open this link. 
Can you send me link to Layer. Click right on layer and use "copy link".
Zrzut ekranu 2023-08-18 o 09 47 21

**Comment by pspaczek** [comment]
@AlanLes I found it. But it's only one side-panel with this design 🙈

**Comment by AlanLes** [comment]
https://www.figma.com/file/mkUqjjL1moaA8FQEOIv2wM/%5BWIP%5D-mgp?type=design&node-id=4301-71883&mode=design&t=lFgxuTXBYbE2wLtB-0
@pspaczek here you have all the products (Intake, PTFU, Triage) with a unified design. 
As you can see - the transition is common for all of them, so if the ui-kit is **our-product-first**, I see no point in continuing with the old design system across the whole ui-kit, even if there are breaking changes.

**Comment by pspaczek** [comment]
@AlanLes I made PR to your PR with my proposal. 
1. IMO you have a broken design :(; https://www.figma.com/file/2p8nMM7W88FU6r0kA52fAA/MGP-Component-Library?type=design&node-id=147-16133&mode=dev here I have a design for all side-panel. No padding in Back and Cross buttons for example. 
2. I add stories for Conditions; Patient Education and Mega Menu to show the customization's ease. 
3. Fine w can "remove" the cross from the top because with my proposal you can make if you need it.

**Comment by pspaczek** [comment]
and your PR is incomplete :( Are you check the storybook after your changes? When I run it I have a first huge issue (inline subtitles 🙈 )
Zrzut ekranu 2023-08-21 o 11 37 18

**Comment by AlanLes** [comment]
OK, @pspaczek I've merged your PR, looks like we can go with it, hm? :)

**Pull request merged**
