### PR TITLE
feat: add custom table component and toolbar addon for design system

### LINKED ISSUE #80: [FEATURE]: add table component for design system
The new table component should be similar to the table in figma design files.

The table should consist of the following columns:
- an example that shows the changes
- name
- description
- default value
- control

### PR DESCRIPTION
**Pull request by ArkadiuszKrzymienski**
# Related issue
Close #80 

# Scope of work
- added a custom `CssPropertiesTable` component and replaced a storybook `ArgsTable` component.
- added an example column to the table
- fixed a color picker storybook controls. Now, we don't need to reload the window after resetting his state.
- updated `cssProperties` parameters for stories
- improved grouping of CSS custom properties into sections in a table
- added a toolbar addon. It can show/hide/reset edited custom styles for stories

# Screenshots

Zrzut ekranu 2023-01-5 o 08 47 27

Zrzut ekranu 2023-01-5 o 08 49 15

### CODE REVIEW

**Comment by pspaczek** [comment]
Zrzut ekranu 2023-01-12 o 18 04 31
`Default colors` should be before `Color Decisions`

**Comment by pspaczek** [comment]
Zrzut ekranu 2023-01-12 o 18 05 39
Please use white only for -600, -700, -800 and -900

**Comment by pspaczek** [comment]
Zrzut ekranu 2023-01-12 o 18 07 40
Please use the same visualization element like in our Figma 
Zrzut ekranu 2023-01-12 o 18 08 41
Zrzut ekranu 2023-01-12 o 18 08 57
Zrzut ekranu 2023-01-12 o 18 08 27

**Comment by pspaczek** [comment]
Please present Typography without border's
Zrzut ekranu 2023-01-12 o 18 10 54

**Review by pspaczek — CHANGES_REQUESTED** [review]
this PR is amazing! :) Design systems docs look awesome. But as you know me! We need to make a few improvements to make it better!

**Comment by ArkadiuszKrzymienski** [comment]
I fixed this issue with try catch and I added similar visualization elements as in our Figma

Zrzut ekranu 2023-01-17 o 14 56 54
Zrzut ekranu 2023-01-17 o 14 57 15
Zrzut ekranu 2023-01-17 o 14 57 33
Zrzut ekranu 2023-01-17 o 14 57 45
Zrzut ekranu 2023-01-17 o 14 58 41

**Review by pspaczek — APPROVED** [review]
Awweeesome! LGTM! :thank_you: @ArkadiuszKrzymienski

**Pull request merged**
