### PR TITLE
fix: make PhoneNumber usable externally

### PR DESCRIPTION
**Pull request by kubajmarek**
## Description
- allow usage of PhoneNumber externally, by shifting responsibility of providing translations  to library user
- fix bug where initially selected value wasn't translated
- simplify how custom countryCodes are provided

## Related Issue
Related to https://github.com/infermedica/component-library/issues/380, although it doesn't fix it.

## Motivation and Context
There was an issue with dynamic imports of `i18n-iso-countries` translations which prevented us from using PhoneNumber component externally. I attempted to fix this so we can get future improvements like https://github.com/infermedica/component-library/issues/413 and uncovered some other issues.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sonya0504** [comment]
In the console there is a warning:
image

**Comment by sonya0504** [comment]
in the story `With Custom Country Codes With Timeout`, the button `ui-phone-number-prefix-toggle` after 3sek should display text of the first element on the list like [here](https://component.infermedica.com/?path=/story/molecules-phonenumber--with-custom-country-codes-with-timeout), but it stays empty

**Comment by sonya0504** [comment]
In the file `UiPhoneNumber.stories.ts` there are some type errors like this one:
image

**Comment by kubajmarek** [comment]
> in the story `With Custom Country Codes With Timeout`, the button `ui-phone-number-prefix-toggle` after 3sek should display text of the first element on the list like [here](https://component.infermedica.com/?path=/story/molecules-phonenumber--with-custom-country-codes-with-timeout), but it stays empty

Out of curiosity, what's the purpose of this timeout? 🤔

**Comment by kubajmarek** [comment]
TODO: if countryCodes is passed (without US), but not modelValue.prefix, nothing will be selected. Probably 1st value should be selected.

**Comment by kubajmarek** [comment]
TODO: `selectedCountryInfo` should work on either `countryCode` or `code`, not only `countryCode`, in case we've just phone number, without meta info.

**Comment by sonya0504** [comment]
> > in the story `With Custom Country Codes With Timeout`, the button `ui-phone-number-prefix-toggle` after 3sek should display text of the first element on the list like [here](https://component.infermedica.com/?path=/story/molecules-phonenumber--with-custom-country-codes-with-timeout), but it stays empty
> 
> Out of curiosity, what's the purpose of this timeout? 🤔

This story I added to show how the behaviour PhoneNumber when waiting for custom prefixes list

**Review by AlanLes — APPROVED** [review]
LGTM 👍

**Review by AlanLes — DISMISSED** [review]

**Review by sonya0504 — APPROVED** [review]

**Comment by kubajmarek** [comment]
Update: after looking into "US" being chosen by default, I thought that maybe we sometimes don't want to do that. Discussed this with Piotr and we came up with new design, with possibility of placeholder:
https://www.figma.com/design/2p8nMM7W88FU6r0kA52fAA/MGP-Component-Library?node-id=7220-19068&t=fgffiEVNqaDSatCl-0

Unfortunately, this means new error too. 😅 
Currently the error handling is done a bit wonky, since it doesn't do any validation on itself - but I think it's fine as a starter.

**Review by pspaczek — APPROVED** [review]

**Review by AlanLes — APPROVED** [review]

**Pull request merged**
