### PR TITLE
fix: voiceover issues for UiMultipleChoices component

### LINKED ISSUE #218: [BUG] Voiceover doesn't work correctly for UiMulitpleChoices component
Voiceover doesn't read the legend of the fieldset.
Issue appears on chromium and firefox browser.

Current result

https://github.com/infermedica/component-library/assets/17556031/8e56b707-f492-4824-8690-127613085ac7

Expected result:

https://github.com/infermedica/component-library/assets/17556031/cb901f1f-bd41-4f9b-bd40-86ad2d936472

### PR DESCRIPTION
**Pull request by mateuszkulpa**
### Related issue
Closes #218  

### Scope of work
- Fixes only issue on chromium-based browsers. Still, there is an issue with firefox.

### Recording

https://github.com/infermedica/component-library/assets/17556031/8b132453-fc5a-454a-a193-4b37c0d7f36b

### CODE REVIEW

**Comment by mateuszkulpa** [comment]
@pspaczek I found a possible way to fix it on Firefox too.
We would have to move input outside the label in UiRadio.

From:
```
<label><input type="radio> ... </label>
```

To: 
```
<label></label>
<input type="radio> ... 
```

WDYT?

**Comment by pspaczek** [comment]
Without changes from this PR? Because now you change `ul` to `div` but `li` still be `li` ;)

**Comment by pspaczek** [comment]
> @pspaczek I found a possible way to fix it on Firefox too. We would have to move input outside the label in UiRadio.
> 
> From:
> 
> ```
> <label><input type="radio> ... </label>
> ```
> 
> To:
> 
> ```
> <label></label>
> <input type="radio> ... 
> ```
> 
> WDYT?

It should be changed in UiCheckbox and UiRadio, I think :)

**Comment by mateuszkulpa** [comment]
@pspaczek I only changed `role` from `tag`. I'd leave it as it is, changing the markup of radios and checkboxes is a bit more risky in terms of plans for the triage release.

**Review by pspaczek — APPROVED** [review]
:thank_you: @mateuszkulpa this solution looks like the best way for now

**Pull request merged**
