### PR TITLE
feat: use vue-docgen-api to trace changes in components

### LINKED ISSUE #16: [FEATURE] Use vue-docgen-api to trace changes in components
**Why we need it**
We want to trace components API changes to prevent unhandled breaking changes.

**How we can do it**

* We can use [vue-docgen-api](https://vue-styleguidist.github.io/docs/Docgen.html#api) to scrap components (and _internal components) API (props, slots, emits).
* Make components iteration function reusable and allow to pass some callback to it (as single and as array of callbacks).
* Save results of `vue-docgen-api` to `components-api-lock.json`.
* Add script to detect diffs between `components-api-lock.json` on `develop` branch and on the current branch.  

* Its only my proposal to solve this issue. Feel free to add improvements to my proposition.

### PR DESCRIPTION
**Pull request by ArkadiuszKrzymienski**
# Related issue
Close #16 

## Scope of work
- add a reusable helper `pathsComponentLoop` to iterate through a components and allow pass some callbacks to them.
- generate and save `vue-docgen-api` results to`components-api-lock.json`
- refactor `create-index.js` - use `pahtsComponentLoop` helper to iterate over components
- Add a script `check:components-api` to detect differences in `components-api-lock.json` file between the development branch and current changes.

### CODE REVIEW

**Comment by ArkadiuszKrzymienski** [comment]
- For now, the output of the diffs in the `components-api-lock` file looks like this 👇

Zrzut ekranu 2022-10-10 o 10 26 52

- I want to get the following list pattern
`<component_name> <added | removed> <prop | slot | event ...> <differences>`

**Comment by ArkadiuszKrzymienski** [comment]
Now the results looks like this 👇

Zrzut ekranu 2022-10-14 o 09 10 18

**Comment by pspaczek** [comment]
@ArkadiuszKrzymienski this script is amazing, I will do CR to check code and give you feedback but now I have 2 issue to solve 👍. 

Maybe we can use `console.table` instead console.log and return a table of changes similar to Release Notes e.g.

**UiMultipleAnswer**
Props Changes
<table>
<tr>
<th>Props</th>
<th>Status</th>
<th>Details</th>
<tr>
<tr>
<td>`items`</td>
<td>Added</td>
<td></td>
</tr>
<tr>
<td>`hintAlertAttrs`</td>
<td>Added</td>
<td></td>
</tr>
</table>
Slot Changes
<table>
<tr>
<th>Slot</th>
<th>Status</th>
<th>Details</th>
<tr>
<tr>
<td>`list-item`</td>
<td>Removed</td>
<td>bindings: `choice`, `modelValue`, `updateHandler`, ...</td>
</tr>
</table>
And second idea. Maybe we can save `diffs` to .json and add it to git-ignore. Thanks for that we can add soon some UI to this feature.

**Comment by ArkadiuszKrzymienski** [comment]
a few changes: 🙂 
- print diffs as a table, now looks like this 👇

Zrzut ekranu 2022-10-19 o 18 26 38

- add support for two args:
> - `--branch` default value: `develop`  
> - `--outputFile` default value: `components-api-diffs.json` 

- save the diffs in the output file, looks like this 👇

Zrzut ekranu 2022-10-19 o 18 29 28

**Pull request merged**
